<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NUV-5CG1152V3W" failures="1" tests="1" name="Purchase order with Logged in user" time="5.902" errors="0" timestamp="2023-01-25T13:34:36 EET">
  <testcase classname="ShoppingTests.TESTS_PurchaseWithLoggedUser" name="t1_LoginAndPurchase" time="4.676">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [120]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [120]
at Pages.SHOPPING_CART_PAGE.assertTotalTop_value(SHOPPING_CART_PAGE.java:281)
at ShoppingTests.TESTS_PurchaseWithLoggedUser.t1_LoginAndPurchase(TESTS_PurchaseWithLoggedUser.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- t1_LoginAndPurchase -->
</testsuite> <!-- Purchase order with Logged in user -->
