<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NUV-5CG1152V3W" failures="1" tests="6" name="Default test" time="119.056" errors="0" timestamp="2023-06-12T17:42:55 EEST">
  <testcase classname="ShoppingTests.DifferentCalculations" name="t1_calculationsWithVAT_Country" time="18.971"/>
  <testcase classname="ShoppingTests.DifferentCalculations" name="t2_calculationsWithoutVAT_Country" time="17.193"/>
  <testcase classname="ShoppingTests.DifferentCalculations" name="t3_FacadeRegisteredAccountNoVAT" time="20.349"/>
  <testcase classname="ShoppingTests.DifferentCalculations" name="t4_FacadeGuestAccount" time="15.805"/>
  <testcase classname="ShoppingTests.DifferentCalculations" name="t4_FacadeGuestAccountShippingAddress" time="19.914">
    <failure type="java.lang.AssertionError" message="expected [101.0] but found [123.2]">
      <![CDATA[java.lang.AssertionError: expected [101.0] but found [123.2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:701)
at org.testng.Assert.assertEquals(Assert.java:712)
at Pages.FascadePage.assertionsNoVat(FascadePage.java:211)
at ShoppingTests.DifferentCalculations.t4_FacadeGuestAccountShippingAddress(DifferentCalculations.java:333)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- t4_FacadeGuestAccountShippingAddress -->
  <testcase classname="ShoppingTests.DifferentCalculations" name="t5_FacadeGuestAccountShippingAddressWithVAT" time="18.833"/>
</testsuite> <!-- Default test -->
